morenoh149/react-native-contacts

README.md

Fixes https://github.com/rt2zz/react-native-contacts/issues/8

Add explanation for iOS limitation

---

README.md
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java

* fix error 14 on real device
* peform query only once against [Contactables table](http://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Contactables.html)
* differs from iOS api in that the entire display name is passed into the `givenName` field

Fix android getAll

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java

Exit subroutine when no contacts are found

---

README.md
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java

* fixes #24
* follows code outlined in https://developer.android.com/guide/topics/providers/contacts-provider.html

Android addContact

---

ios/RCTContacts/RCTContacts.m

Fixes https://github.com/rt2zz/react-native-contacts/issues/15

Return empty string instead of nil for missing thumbnail

---

README.md

Newer versions of RN require different instructions.

Update README.md for adding the package

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java

Fix to make this work with Android version 4.1.2 (API level 16)

Fix to make this work with Android version 4.1.2 (API level 16)

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

- fix java.lang.NullPointerException caused by toLowerCase() in ContactsProvider.java
- Issue happened only on a HTC device....

Fix java.lang.NullPointerException in ContactsProvider

---

README.md
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

Added support to return the 'me' profile along with the other contacts

Added support to return the 'me' profile along with the other contacts

---

ios/RCTContacts.xcodeproj/project.pbxproj

Set iOS Deployment Target to 7.0

---

README.md
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java

Adds the checkPermission and requestPermission functions on android to make the library compatible when calling those functions.
Fixes #33

Add checkPermission for Android

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

Hey, there!
I've added contact images for Android. I've tested this pretty thoroughly with my application, seems to work fine.
Let me know if there's anything you need me to do!

Add Android contact images.

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

related to the following issue: https://github.com/rt2zz/react-native-contacts/issues/91

check if cursor is null in while (trying to prevent exception)

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
ios/RCTContacts/RCTContacts.m

fix file handle leaks that are causing app crashes if there are many contacts with icons

fix file handle leaks that are causing app crashes if there are many contacts with icons

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
android/src/main/java/com/rt2zz/reactnativecontacts/ReactNativeContacts.java

applied default formatting from android studio

applied default formatting from android studio

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

Added Android support for company and jobTitle
(fixes #74, refs #73)

Android company support

---

README.md
android/build.gradle
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
android/src/main/java/com/rt2zz/reactnativecontacts/ReactNativeContacts.java
ios/RCTContacts/RCTContacts.m

* android performance fix - no longer repeatedly creating files for contact icons
* added addresses for both iOS and android

android performance fix + added addresses

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

* reverting use of SOURCE_ID field (in favour of CONTACT_ID ) as it doesn't seem to work on all devices

 * reverting use of SOURCE_ID field (in favour of CONTACT_ID ) as it doesn't seem to work on all devices

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
ios/RCTContacts/RCTContacts.m

Help wanted for adding nickname and note on Android.

Support prefix, suffix, department on iOS & Android.  Support Nickname, Note on iOS.

---

ios/RCTContacts/RCTContacts.m

Applied @npomfret fix 600bb21 to phone numbers as well

Fix - include labeless phone numbers as other

---

README.md

move installation closer to top

---

README.md

* fixes https://github.com/rt2zz/react-native-contacts/issues/153
* document how value is needed for app store submission

Document contact usage string for App Store

---

README.md

Missing hasThumbnail in the example.

[README.md] Add hasThumbnail in Example Contact Record

---

index.d.ts
package.json

Typescript declaration file

---

README.md

added installation information with yarn

---

README.md
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
index.d.ts
ios/RCTContacts.xcodeproj/project.pbxproj
ios/RCTContacts/RCTContacts.h
ios/RCTContacts/RCTContacts.m

create a contact with the corresponding new to-be-saved user data and display in a contactsUI view

Allow contacts to be created via contact form launch

---

README.md
android/src/main/java/com/rt2zz/reactnativecontacts/ReactNativeContacts.java
index.d.ts
ios/RCTContacts/RCTContacts.m
package.json

Adds the ability to import the "birthday" field from your contacts. Both iOS and Android. Because contacts' birthdays may or may not include the year, it's returned as a dictionary rather than a date representation.

Adds birthday to contacts import

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java

Fix for issue where postal addresses were not included in update
operation

Add ability to update postal addresses

---

README.md

Fix directory path of xcode project

Fix typo in README to manual installation

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

fixes crash when birthday is not in the expected format (#279, #288)

---

index.d.ts

changed Number to number for correct use in TypeScript in other methods

Fix birthday type script declaration

---

android/.gitignore
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

UpdateContact Method is updating all numbers in the contact instead of a specific number is fixed.

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

Email update bug fixed by adding Id.
fixes #191

Email update bug fixed by adding Id.

---

README.md

I wanted to setup the project manually and needed to add these changes myself.
I noticed the [issue](https://github.com/rt2zz/react-native-contacts/issues/319) requesting the instructions, so I thought I would submit the PR to add them to the README.
Glad to make any changes!  And thanks for putting this great project together!
Fixes #319

Update README For Android Manual Installation

---

README.md

This PR updates the readme to include a note for those who wish to support older versions of Android (API level <= 22)
Fixes #331

Readme update for older Android versions

---

android/build.gradle

https://github.com/rt2zz/react-native-contacts/issues/337#issue-388969292

fix issue #377

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

- Use rawContactId instead of contactId
- Use switch instead of else if

Preventing merge contacts if device has duplicates

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

This commit replaces the instances of `AsyncTask.execute(new Runnable()
{` with `AsyncTask`s that are then executed in a different thread.
Credit to @jslz who brought this up in Issue #237.

Run async tasks asynchronously.

---

README.md
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
index.d.ts
ios/RCTContacts/RCTContacts.m

getContactById

---

android/build.gradle
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
android/src/main/java/com/rt2zz/reactnativecontacts/ReactNativeContacts.java

Since React Native will be switching to use Android X from 0.60.0 and it's in phase of RC, now it is a good timing to migrate this project to also use Android X IMO.

Android X migration

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

fixes https://github.com/rt2zz/react-native-contacts/issues/327#issuecomment-508717375

added 'displayName' field

---

ios/RCTContacts/RCTContacts.m

Adds support for iOS 13 - Apple doesn't allow access to the note field on iOS 13.
Fixes #404

Remove note field from contacts

---

README.md

I noticed the numbering in the README is a bit misleading. I raised this PR to fix the inaccurate numbering.
**Screenshots**
Before:
After:

Update inaccurate numbering in the README

---

README.md
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
example/App.js
ios/RCTContacts/RCTContacts.m

This is nearly a copy and paste of the getContactsByPhoneNumber implementation with the minimum necessary bits swapped out to search by email address.  It has been tested on both platforms.
Edit: drop lame excuse for being lazy because it isn't that much work to add to example / readme.

getContactByEmailAddress() - iOS and Android - working

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java

Allow fomattedAddress in openContactForm android

---

ios/RCTContacts/RCTContacts.m

https://github.com/rt2zz/react-native-contacts/issues/408

Fix iOS opening contact form

---

README.md
index.d.ts

You miss to add the definition of getCount for typescript and in documentation as well

Add getCount in typescript

---

README.md
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
example/App.js
index.d.ts
ios/RCTContacts/RCTContacts.m

Hello guys,
I added the "editExistingContact" method to add a number to an existing contact.
I created the method for both android and ios. I'm not an Objective-C expert and I hope I have done a good job.
Jonny

Add number to an existing contact

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java

I added the usage of the instant message address fields for getContacts().
Also added a fix for Instant Messengers TYPE field.

Add instant message information support for Android

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java

fix issue 548. prevent from add new contacts as null/undefined

---

README.md
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
example/App.js
example/ios/Podfile
example/ios/Podfile.lock
ios/RCTContacts/RCTContacts.m

I made this (incomplete) draft PR migrating from Callbacks to Promises.
It's make sense ? Could this be useful ? 
it will a Breaking Change.
What do you think ?

poc: migration to promises

---

example/App.js
ios/RCTContacts/RCTContacts.m

Fixed exception when calling openContactForm on iOS

---

index.d.ts

Add missing type declaration for getContactsByEmailAddress method
Fixes #444

Add getContactsByEmailAddress type declaration

---

README.md

#647 README.md syntax error fix getAll

---

README.md
ios/RCTContacts/RCTContacts.m

RELATES TO: https://github.com/morenoh149/react-native-contacts/issues/641#issuecomment-983040022

Fix month to be valid values between 1-12 + consistency across platforms

---

index.d.ts
ios/RCTContacts/RCTContacts.m

Dismiss the outermost modal only when closing the contact form and add viewExistingModal method types

---

android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java

This Pull request addresses the issue
[https://github.com/morenoh149/react-native-contacts/issues/678](https://github.com/morenoh149/react-native-contacts/issues/678)

fix: crash on cursor failure

---

README.md
android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
index.d.ts

Note: This only works on Android as Apple doesn't provide this
information :(
I read CONTRIBUTING.md after I created the patch, so not sure if you will want to merge this given it is Android only.
Fixes #90

Add a field to indicate if the contact is starred

---

index.d.ts

Update types for contact fields that may be null

---

ios/RCTContacts/RCTContacts.h
react-native-contacts.podspec

fix: ios id<CNContactViewControllerDelegate>

---

README.md
ios/RCTContacts/RCTContacts.mm

Hi!
This PR addresses the following updates:
- fix build error (https://github.com/morenoh149/react-native-contacts/issues/756)
- add conditional logic for iOS 18
- update README with notes on limited feature usage
Thank you.

Fix build issue due to limited contact permission

---

ios/RCTContacts/RCTContacts.mm

Fix presentation issues for iOS 18

fix(presentation): Fix presentation issues for iOS 18 (#1)
