- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
fixes https://github.com/rt2zz/react-native-contacts/issues/10
> fix cursor check to null

- README.md
- ios/RCTContacts/RCTContacts.m
Fix issue #22 by adding `.png` to the tempfilePath. It can now be sourced directly in the `<Image/>` tag by the `uri` key.
> Fix thumbnails not displaying

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
Via [this StackOverflow](http://stackoverflow.com/questions/13080540/what-causes-androids-contentresolver-query-to-return-null), it looks like `ContentResover.query` can return `null` when there's nothing to resolve or the resolver is not available.
The crash report [can be found here](http://crashes.to/s/7bc64015c82)
Ideally I wanted to avoid `loadContactsFrom(cursor)` all together when there's no `cursor`, but didn't have time to refactor too much.
> Bugfix - Null pointer exception on Cursors

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
> String SOURCE_ID read/write:
> 
> String that uniquely identifies this row to its source account. Typically it is set at the time the raw contact is inserted and never changed afterwards. The one notable exception is a new raw contact: it will have an account name and type (and possibly a data set), but no source id. This indicates to the sync adapter that a new contact needs to be created server-side and its ID stored in the corresponding SOURCE_ID field on the phone.
> Use SOURCE_ID if we can for a better ID (on android)

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
Getting all the contacts is a heavy operation, and seems to cause significant performance impact to apps while it's running despite being called asynchronously from React Native.
In my testing I've identified that by ensuring getAll() runs completely on a background thread using AsyncTask, the performance of the React Native app is unaffected while it runs.
> Run getAll() in a background thread on Android to improve performance

- ios/RCTContacts/RCTContacts.m
uses the caches dir to store the images, and gives them more sensible (predicatble) filesnames
> more sensible way to copy the image icons (no functional change)

- ios/RCTContacts/RCTContacts.m
`nil` labels and values aren't valid and are causing a crash when trying to add them to a dictionary.
> trying to guard against invalid data

- ios/RCTContacts/RCTContacts.h
In react-native 0.40 they moved ios headers to React namespace
> ios: Update headers for RN 0.40.

- ios/RCTContacts/RCTContacts.m
Made all methods return a 'denied' error if permissions are not set up
GetAll no longer lazily requests permissions so its behaviour is more consistent with the other methods
Upgraded remaining methods using the old 'AB' api to use the new CNContactsStore api
> 3 ios improvements (please squash when merging)

- README.md
- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
- ios/RCTContacts/RCTContacts.m
- package.json
This allows one to match a string to a contact's first, middle or last name on the native side. It allows one to not have to pass the entire list of contacts to ReactNative, thus speeding up situations in which a user may have hundreds or thousands of contacts.
Closes #167
> Issue #167 : Implement native filtering by string

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
- ios/RCTContacts/RCTContacts.m
1) Noticed "region" line was set to "city", maybe copy-paste error from line 189?
2) According to Apple docs for [CNPostalAddress](https://developer.apple.com/reference/contacts/cnpostaladdress) it seems this field is called "state"?  I left the resulting property name as "region" so as to not make a breaking change for anyone currently using it.
Let me know if I am wrong in either of those assumptions.
> fixed typo "city" -> "state"

- android/src/main/java/com/rt2zz/reactnativecontacts/ReactNativeContacts.java
React-Native 0.47 change log: https://github.com/facebook/react-native/releases/tag/v0.47.0
I will leave updating the Readme to you since you will have to specify the different versions.
> As of RN 0.47 modules no longer need to override createJsModules.

- README.md
- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
- ios/RCTContacts/RCTContacts.m
- package.json
PostalAddresses will now be added with AddContact
Fixed for both iOS and Android
Follow updated README for the correct formatting in AddContact 
Solving issue [#210](https://github.com/rt2zz/react-native-contacts/issues/210)
Looks like someone already created a [test for this](https://github.com/morenoh149/react-native-contacts-test/pull/3)
> Add PostalAddresses for ios and android

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
Forgot this little function! It's called on line 220 but I forgot to include it. This is in reference to my last [PR](https://github.com/rt2zz/react-native-contacts/pull/212) that added PostalAddresses for both iOS and android. iOS is working fine, Android is broken until this gets merged in.
> Bug fix for Android PostalAddress

- README.md
Just fixes a super-quick syntax error in the README. Thanks for the great library!
> Add missing hyphen to README

- ios/RCTContacts/RCTContacts.m
> Module RCTContacts requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
> [iOS] Fix requiresMainQueueSetup warning

- ios/RCTContacts/RCTContacts.m
Fixes a bug where updating a contact’s postal address on iOS did not
properly save the postal code / zip code field
> Fix for saving postal codes

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
Description:
A compile error while running **compileDebugJavaWithJavac** gradle task
The error log:
```
Task :react-native-contacts:compileDebugJavaWithJavac FAILED
/.../node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java:299: error: cannot find symbol
Log.w("ContactsProvider", e.toString());
^
symbol:   variable Log
location: class ContactsProvider
1 error
```
fixes #298
> Added android.util.Log dependency FIX #298

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
- ios/RCTContacts/RCTContacts.m
Android: 
1. **addContact** : now uses thumbnailPath to get the file it points to so it can decode a Bitmap and associate to the respective Contact. From my tests, if the photo is obtained from an Image Picker and has a path that starts something like "file:///path/to/file", the prefix "file:///" should be removed before saving to thumbnailPath property - in the above example, should be: "/path/to/file". **IOS** version already implemented this by default.
2. **deleteContact**: implemented. Returns (error, recordID), where recordID is the ID of the deleted record in case of successful deletion.
closes #161
> addContact, updateContact, deleteContact improved/implemented with feature parity in both Android and IOS.

- README.md
- android/src/main/AndroidManifest.xml
This PR automatically adds the `READ_CONTACTS` permission to the manifest. Since android has the manifest merge feature, and this library at least always needs the `READ_CONTACTS` permission this will add it automatically.
> Add the read contacts permission to the manifest

- android/build.gradle
Fixes https://github.com/rt2zz/react-native-contacts/issues/303
Enforcing a compile SDK version breaks compilation for people that don't have it installed. The app itself could be using another SDK version and this package does not respect that.
RN App compilation fails with errors like
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-contacts:platformAttrExtractor'.
> A failure occurred while executing com.android.build.gradle.internal.actions.AttrExtractor
> ~/Library/Android/sdk/platforms/android-25/android.jar (No such file or directory)
```
I've changed the gradle config to respect root project's config in terms of compile, sdk and build tools version. It still falls back to the current defaults if the variables aren't defined. …
> Cleanup Gradle config

- README.md
- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
- ios/RCTContacts/RCTContacts.m
Addresses issue #310: Add support for Websites/ URLs for contact creation(https://github.com/rt2zz/react-native-contacts/issues/310)
Adds new URL functionality and incorporates support for Notes from previous PR's that currently have merge conflicts:
- added "note" property [#188](https://github.com/rt2zz/react-native-contacts/pull/188)
- Added support for Note field in iOS [#154](https://github.com/rt2zz/react-native-contacts/pull/154)
Brief description:
- Adds url and note functionality for both iOS and Android
- Users will now see url and note information when pulling in contacts (see example in README)
- Test additions here have been added to /morenoh149/react-native-contacts-test [#8] (https://github.com/morenoh149/react-native-contacts-test/pull/8)
> Add url and note support for react-native-contacts

- README.md
- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
I encountered an issue where when calling `updateContact` on android, it would insert the phone numbers and emails leading to multiple duplicates, essentially the same issue as #332.
The expected behaviour is now consistent with iOS. If you call updateContact with the new contact information, instead of inserting the email addresses and phone numbers (leading to duplicates), it now actually updates them.
> updateContact update phone numbers and emails instead of insert [Android]

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
Commit 9ffadc0: 
Added code for updating postal addresses. I'm basically using the same code used in addContact except it updates instead of insert. This addresses issue  #345 
Commit 9a51c5a:
Addresses a few issues with @luucv 's solution to #332 
1. Stop the delete from running if phones/emails are not present as keys in the argument for updateContact.
2. switch from CONTACT_ID to RAW_CONTACT_ID as reference for deleting because there was problem deleting info added by react-native-contacts.
Commit 871bd49:
Allow custom labels.
Before, we only supported TYPE update. We convert labels to type using mapStringToPhoneType function and only updates the type. This only works for Android's default label. Any unrecognized label is default to OTHER TYPE, and the actual value of the label was …
> [Android] Several Fixes with updateContact

- android/build.gradle
While building the project we get the following warning. The solution is very simple. All we have to do is change the keyword from compile to implementation and it works.
```
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```
> Removing build level warning by moving from compile to implementation

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
When updating a contact on Android a  NoSuchKeyException(name) are being sent for missing keys, city/state etc. If they aren't present. Patch checks if the key is present before trying to read the value.
> Fix for no such key exceptions being thrown on update contact

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
Fixed issue where contactId were overwritten by rawContactId. Now contacts are being mapped based on contactid again like 2.2.5 and older. This solves the issue with duplicated contacts on getAll().
> Fixed issue with update and delete not working on android

- ios/RCTContacts/RCTContacts.m
NSLog print the logs in release mode as well. Its better to use RCTLog as that will be printed only in debug builds and governed by RCTLOG_ENABLED
> Replacing NSLog with RCTLog

- ios/RCTContacts/RCTContacts.m
addresses issue #169
This fix only applies to iOS
When fetching the file path for a thumbnail image, compare the contact thumbnail image file contents with the currently cached image contents. If they do not match, update the file.
> Update iOS contactImageData when it changes

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
This just fixes the issue where contact birthdays are returned as null. Repeat of #334
> Fix for null birthdays on android

- package.json
I recently noticed that upgrading `react-native-contacts` added `react-native-cli` as dependency to my project. Having this as direct dependency for project might cause few issues (like overwriting global rn-cli version).
It was introduced in [this commit](https://github.com/rt2zz/react-native-contacts/commit/20b444b8a776dca498a181c537cab5028a5eeb73). And based on commit description, it should be added as devDependency back then.
> Move react-native-cli to devDependencies

- ios/RCTContacts/RCTContacts.m
This PR is to allow thumbnail pictures to show on search. For whatever reasons, it was disabled.
> fix(RCTContacts): Fix thumbnail path missing on string search

- react-native-contacts.podspec
fix cocoapods error "fatal: unable to find remote helper for 'git+https'"  => add explicit git repo source URL in podspec file
> fix podspec file

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
- example/App.js
- ios/RCTContacts/RCTContacts.m
Added methods for iOS and Android to return a count of all contacts. iOS loops over all contacts to get the total - may be a better way of doing this.
You can test it by running:
```
Contacts.getCount(count => {
console.log('Total contacts: ' + count);
});
```
> Add contacts count feature

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
When I request contacts data on android using `getAllContacts` method, I receive empty array with `urlAddresses` even when the contact has Website data.
It happens because we don't map `Website.CONTENT_ITEM_TYPE` record to contacts data.
This PR fixes it.
Support for urlAddresses was introduced in PR https://github.com/rt2zz/react-native-contacts/pull/329
Here is related issue which should be also fixed by this PR https://github.com/rt2zz/react-native-contacts/issues/436
fixes https://github.com/rt2zz/react-native-contacts/issues/436
> Fix empty urlAddresses on Android

- index.d.ts
- ios/RCTContacts/RCTContacts.m
The back button that is implemented to cancel the new contact form is not supporting a custom label. This commit implements this behavior by adding backTitle to the interface.
> Add configurable option to set back button title.

- README.md
- android/src/main/AndroidManifest.xml
Certain applications that target Android os versions prior to SDK 23 (Android M) may want to opt out of using contacts all together on those downlevel os versions since they require the user to agree to the contacts permission when a user installs the application.
> Remove contacts permission from manifest

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
On Android, in certain cases, the string returned from the contacts db was null, and NullPointerException was unhandled resulting in a crash. This PR handles the exception so if a contact has a null birthday, we can still import the contact excluding the birthday, and the app won't crash. I'm not sure why some contacts' birthdays were coming back as null and could not replicate it on my end, but hopefully this fixes #355  in the sense that it won't crash anymore :P 
fixes #355
> Fix Android null birthday crash

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
We are using a lot `getContactsByPhoneNumber` to retrieve a bunch of contacts. But if your address book is big and you are looking for a lot, some users have ThreadPool error.
With AsyncTask.THREAD_POOL_EXECUTOR we are able to stack 5 threads in the same time and we could  stack 128 threads  => https://medium.com/@arj.sna/android-multiple-asynctasks-78b2f847a2ec
In fact, we don't really have all this method in parallel. The serial mode is good enough and the thread pool size has no limit.
> fix(android): use SERIAL_EXECUTOR instead of THREAD_POOL_EXECUTOR

- README.md
- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
- example/App.js
- example/package-lock.json
- example/package.json
- index.d.ts
- ios/RCTContacts/RCTContacts.m
Note field support for iOS has been cut in commit 02db1fef8200eeb26f1e1362ccd93baca772e0bf (5.0.2) due to an access limitation by Apple. This error can be prevented by providing a valid entitlement file and granting permissions for using that entitlement. The iOS code has been enhanced with an optional method for enabling access to the contact's notes again. The description of how to create a valid entitlement file has been added to the README.md.
The optional `enableNotesUsage(boolean)` function ensures the functionality of the former code without needing any alterations. The contacts can be used as usual without accessing the contact note field. By calling `enableNotesUsage(true)`, the note functionality will be enabled.
Android won't be affected by these changes since the notes are …
> Reenabling notes for iOS

- ios/RCTContacts/RCTContacts.m
When using `openContactForm` modal In iOS 13, the status bar and the background color disappears. Also, the modal navigation title overlaps with the icon showing the picture of initials of a contact. This is caused in part by the latest changes in iOS [Modality](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/modality/) being effective as of iOS 13.
So, a good solution would be showing the contact form pretty much in fashion of how other apps like Mail does: 
- It hides the title in the navigation bar since it overlaps with the uppercase initials icon.
- Adds status bar view and set it to black color when openContactForm appears.
- Removes status bar from view on Cancel or Done, so it doesn't remain visible when closing the contact form.
> Fixing openContactForm modal appearance in iOS 13+

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
This update operation currently replaces all rows in the `ContactsContract.Data` table for the given `CONTACT_ID` with `StructuredName` data. This replaces all data with mimetype `group_membership`, `note`, `contact_event`, `relation`, `contact_misc` with the contact's `StructuredName`. This PR adds the correct `where` clause to the `StructuredName` update operation so that only rows with `name` mimetype are updated with the `StructuredName` data.
> Fix Android StructuredName Update

- .npmignore
Example directory takes 8.4MB out of total unpacked package size of 8.8 MB. This should greatly reduce the package size.
Results of `yarn pack`:
Before: 7.2M
After: 80K
> Exclude example directory from npm package

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
On an Android Samsung, S8 and S10 updating the ACCOUNT_TYPE and ACCOUNT_NAME will cause the contact to become un-editable from the native contact app.
Fixes #504
Android users on Samsung S8 and S10. Maybe more Samsung models.
[Android docs](https://developer.android.com/reference/android/provider/ContactsContract.RawContacts) (See ContactsContract.SyncColumns.ACCOUNT_TYPE) warn against updating the ACCOUNT_NAME and ACCOUNT_TYPE later. Removing that specific update logic to fix the issue.
Not sure if there is a better way. Happy to work with suggestions. 
None. ACCOUNT_TYPE and ACCOUNT_NAME are not set to null on update.
These are my steps to reproduce on S8.
- Create contact using addContact method
- Update that contact's first name and last using updateContact
- Close the React Native …
> Do not update ACCOUNT_TYPE when updating contact

- ios/RCTContacts/RCTContacts.m
If iOS13 the correct system colors are used for the loading indicator and background
> Dark mode compatibility when loading contact

- ios/RCTContacts/RCTContacts.m
Fixes https://github.com/morenoh149/react-native-contacts/pull/430#issuecomment-636049810
Since the calling method is returning an objective-c array in the response callback. by returning nil rather than a [NSNull null], object you are trying to insert nil into an array, which is invalid, and leads to the crash. Its better in the transition between React native and Objective-c to return NSNull objects. This is what the React native side would expect as a response for failure.
> Fixes getContactById crash when contact no longer exists

- ios/RCTContacts/RCTContacts.m
The removed code was never used!
The return value of [contactStore containersMatchingPredicat:] is not used, so the code is redundant. Also we've seen crash reports on this line (when contactStore.defaultContainerIdentifier is nil).
> Fixes crash bug when getting all contacts if defaultContainerIdentifier was null

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
Adds missing note attribute to `openContactForm()` and `updateContact()` on Android. 
[Already works](https://github.com/morenoh149/react-native-contacts/blob/master/ios/RCTContacts/RCTContacts.m#L986) on iOS. 
[Already works](https://github.com/morenoh149/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L655) for `addContact()` but for some reason is missing for `openContactForm()` and `updateContact()`.
> Add note to openContactForm and updateContact on Android

- index.d.ts
I'm getting this typescript error
```
src/views/ContactForm/index.tsx:134:30 - error TS2345: Argument of type '{ emailAddresses: { label: string; email: string; }[]; familyName: string; givenName: string; }' is not assignable to parameter of type 'Contact'.
Type '{ emailAddresses: { label: string; email: string; }[]; familyName: string; givenName: string; }' is missing the following properties from type 'Contact': recordID, backTitle, company, middleName, and 11 more.
134     Contacts.openContactForm(newPerson, (err) => {
~~~~~~~~~
```
Changing `(contact: Contact` to `(contact: Partial<Contact>` removes the error.
The contact is not supposed to be required to be complete right?
> openContactForm typing

- react-native-contacts.podspec
Xcode 12 won't build if a module depends on React instead of React-Core. 
More info: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
> fix: xcode 12 compatibility

- index.d.ts
I believe this is the correct transformation to handle the new v6 promise API
Fixes #564
This works for me in local testing on iOS and Android, but I don't use *all* the APIs so while I believe it to be correct it should be checked carefully
Perhaps @28harishkumar could give it a look?
I've pasted in the patch-package version of this change on the related issue for easy testing by others
> fix(types): update Typescript definitions to match v6 promise API

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
Note field was never passed to JS side on Android.
> Fix missing note field

- ios/RCTContacts/RCTContacts.m
This PR is to fix #639 which causes the contact sheet's header buttons and text to be invisible when using dark mode.
It also fixes the problem with the statusBar colour which causes you app's custom statusBar colour to be replaced (This is only noticeable if the phone has a notch)
I have tested this on iOS13.0 (Simulator), 14.7.1 (iPhone 8+) and 15.1 (iPhone X) and it behaves as expected: when in dark mode, the header buttons use the accent colour and the title is white.
The problem:
https://user-images.githubusercontent.com/5883791/140702296-10e7b06a-2062-4484-be6f-8a24654ea225.mov
The fix:
https://user-images.githubusercontent.com/5883791/140702910-1603da10-653d-4ac7-bbd7-629b0df8c87e.mov
> iOS Dark mode contact card header buttons and text invisible

- ios/RCTContacts/RCTContacts.m
`openExistingContact:...` was creating a `UIBarButtonItem` with a `style` of `UIBarButtonSystemItemCancel`.  However `UIBarButtonSystemItemCancel` is not a style, it is a type of item.  Instead we should use `UIBarButtonItemStyleDone`
This will avoid raising a `-Wenum-conversion` error and fixes the bug for the style ending up being the deprecated `UIBarButtonItemStyleBordered` (`0x1`) by accident.
You can verify by enabling `-Wenum-conversion` and `-Werror=enum-conversion` in your compilation.  The current state of the code will fail with a compiler error for using the wrong enum value.  Building with this change will succeed without issue.
> Update RCTContacts.m to use correct UIBarButtonItemStyle constant

- index.d.ts
- Typescript definition of methods for creating and updating contacts is too restrictive, we need to fill all contact values whereas some of them is sufficient (`Partial` added)
- `addContact` should return back created contact (to get `recordID`) instead of `void`
- `urlAddresses` were missing
> fix(typescript): improve signatures and add url addresses

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
- No functional change.
- Use checkSelfPermission instead of checkCallingSelfPermission for security.
- This is done to protect against accidentally leaking permissions.
> fix: Use checkSelfPermission instead of checkCallingSelfPermission for security

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java
Hello folks! I found it quite confusing that some labels change to 'other' after the contact import. I made a following change where all labels are translated into the language used in the phone. It also works with user-defined labels.
> support for custom user defined contact labels

- ios/RCTContacts/RCTContacts.m
Fixed this error
[See attached]
> Fix: solved error on ios that prevented the creation of the contacts module

- android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java
There was a crash on pre-6.0 Android devices
`context.checkSelfPermission()` required API level 23
```
Caused by java.lang.NoSuchMethodError: No virtual method checkSelfPermission(Ljava/lang/String;)I in class Lcom/facebook/react/bridge/ReactApplicationContext; or its super classes
at com.rt2zz.reactnativecontacts.ContactsManager.isPermissionGranted(ContactsManager.java:1221)
at com.rt2zz.reactnativecontacts.ContactsManager.checkPermission(ContactsManager.java:1149)
at java.lang.reflect.Method.invoke(Method.java)
...
```
> Use ActivityCompat to check if permission is granted

- README.md
- index.d.ts
- index.ts
- ios/RCTContacts/RCTContacts.mm
- src/NativeContacts.ts
- type.ts
This PR partially addresses [issue #747](https://github.com/morenoh149/react-native-contacts/issues/747).
Added getGroups() function which returns an array of group objects, including identifier and name
I would appreciate feedback from the maintainers on whether I am heading in the right direction and if I should proceed with the implementation of other functions.
Below are the additional functions I am considering implementing:
- getGroup(groupId) - Returns the group matching the provided groupId.
- contactsInGroup(groupId) - Retrieves all contacts within a specified group.
- addGroup(groupDetails) - Adds a new group.
- updateGroup(groupId, updatedDetails) - Updates an existing group's details.
- deleteGroup(groupId) - Deletes a group by groupId.
- addContactsToGroup(groupId, …
> feat: add group functionality

- package.json
since the last pr of migrating `new_arch`
now to import types we have to get it from type.is
and to import the functions we have to get it from index.d.ts
```
import Contact  from 'react-native-contacts';
import { Contact } from 'react-native-contacts/type';
```
I believe since we already have an index.d.ts 
we don't need an extra path here and import everything from one file
so it will look like this 
```
import Contact, {Contact,UrlAddress}  from 'react-native-contacts';
```
> revert `package.json` to get types from `index.d.ts`

- index.d.ts
- ios/RCTContacts/RCTContacts.mm
- src/NativeContacts.ts
- type.ts
hello 
in this pr fixes #758
also, there was an interesting case here
`addGroup(group: Pick<Group, "name">): Promise<Group>;`
`updateGroup(identifier: string,groupData: Pick<Group, 'name'>): Promise<Group>;`
while I was trying to test the lib with the latest rn `0.76.3` I got this error 
`UnsupportedGenericParserError: Module NativeContacts: Unrecognized generic type 'Pick' in NativeModule spec.`
and there is an [issue](https://github.com/facebook/react-native/issues/38769) already opened in react-native 
so I removed Pick and replaced it with just type
> fix undeclared identifier 'CNAuthorizationStatusLimited'

- index.ts
This pull request addresses compatibility issues with React Native 0.77.1 by updating the assignment of the `Contacts` module. The previous implementation utilized `global.__turboModuleProxy`, which has been deprecated in favor of direct TurboModule access via `NativeModules`.
**Changes:**
- Removed reliance on `global.__turboModuleProxy`.
- Updated `Contacts` assignment to use `NativeModules.Contacts ?? NativeContacts`.
In React Native 0.77.1, the `global.__turboModuleProxy` has been deprecated, and direct access to TurboModules through `NativeModules` is now the recommended approach. This change ensures that the `Contacts` module is correctly assigned, maintaining functionality across versions.
**References:**
- [React Native 0.77.0-rc.0 Release …
> Fix: React Native 0.77.1 Compatibility
